import { NextResponse } from 'next/server';
import { withAuth } from '@/lib/withAuth';
import { dbConnect } from '@/lib/mongodb';
import User from '@/models/User';
// Removed OpenAI calls – summaries are generated by /api/summary/* routes
import type { DecodedIdToken } from 'firebase-admin/auth';

interface AstroData {
  year: number;
  month: number;
  date: number;
  hours: number;
  minutes: number;
  seconds: number;
  latitude: number;
  longitude: number;
  timezone: number;
  settings: {
    observation_point: 'topocentric' | 'geocentric';
    ayanamsha: 'lahiri' | 'raman' | 'krishnamurti' | 'sayan';
  };
}

// Cache for storing profile data (in production, use Redis or database)
interface CacheEntry {
  data: ProfileData;
  timestamp: number;
}

interface ProfileData {
  natalChart: Record<string, unknown>;
  currentTransits: Record<string, unknown>;
  astroSummary: string;
  humanDesignSummary: string;
  cumulativeSummary: string;
  generatedAt: string;
  nextUpdate: string;
}

const profileCache = new Map<string, CacheEntry>();
const CACHE_DURATION = 24 * 60 * 60 * 1000; // 24 hours

export const GET = withAuth(async (req: Request, user: DecodedIdToken) => {
  try {
    console.log('Profile API called for user:', user.uid);
    const uid = user.uid;
    const now = new Date();
    
    // Check cache first
    const today = now.toISOString().split('T')[0]; // YYYY-MM-DD
    const cacheKey = `${uid}-${today}`;
    const cached = profileCache.get(cacheKey);
    
    if (cached && (now.getTime() - cached.timestamp) < CACHE_DURATION) {
      console.log('Returning cached profile data');
      return NextResponse.json({
        success: true,
        profile: cached.data,
        cached: true
      });
    }

    // Run database connection and user fetch in parallel with current time setup
    const [, userData] = await Promise.all([
      dbConnect(),
      User.findOne({ uid })
    ]);

    console.log('User data found:', !!userData, 'Has astroDetails:', !!userData?.astroDetails);
    
    if (!userData || !userData.astroDetails) {
      return NextResponse.json(
        { error: 'No birth chart data found. Please complete your profile first.' },
        { status: 400 }
      );
    }

    const natalData = userData.astroDetails;
    
    // Prepare current transit data
    const currentAstroData: AstroData = {
      year: now.getFullYear(),
      month: now.getMonth() + 1,
      date: now.getDate(),
      hours: now.getHours(),
      minutes: now.getMinutes(),
      seconds: now.getSeconds(),
      latitude: natalData.input.latitude,
      longitude: natalData.input.longitude,
      timezone: natalData.input.timezone,
      settings: natalData.input.settings
    };

    // Fetch current planetary positions (no AI involved)
    const currentTransits = await (
      await fetch('https://json.freeastrologyapi.com/planets', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-api-key': process.env.ASTROLOGY_API_KEY || 'YOUR_API_KEY_HERE'
        },
        body: JSON.stringify(currentAstroData)
      })
    ).json();

    const astroSummary = '';
    const humanDesignSummary = '';
    const cumulativeSummary = '';

    const profileData = {
      natalChart: natalData,
      currentTransits: currentTransits,
      astroSummary,
      humanDesignSummary,
      cumulativeSummary,
      generatedAt: now.toISOString(),
      nextUpdate: new Date(now.getTime() + 24 * 60 * 60 * 1000).toISOString()
    };

    // Cache the result
    profileCache.set(cacheKey, {
      data: profileData,
      timestamp: now.getTime()
    });

    return NextResponse.json({
      success: true,
      profile: profileData
    });

  } catch (error) {
    console.error('Error in profile route:', error);
    return NextResponse.json(
      { 
        success: false, 
        error: 'Failed to generate profile synthesis',
        message: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}); 